theme: jekyll-theme-hacker
logo: assets/logo.png
title: hackbar.ch - 27.-30.12.2023 - Bern, Switzerland
tagline: #hackbar - 27.-30.12.2023 - Bern, Switzerland
image: 
  path: /assets/logo.png
github:
  is_project_page: false
  is_user_page: false
exclude: "INSTRUCTIONS.md"
defaults:
  logo: assets/logo.png
  image:
    path: assets/logo.png 
